fname = input("Enter file name: ")
fh = open(fname)
lst = list()
for line in fh:
    line = line.rstrip()
    wds = line.split()
    #s3 = lst.append(wds)
    #print('Words :', wds)
    lst.append(wds[0])
    lst.append(wds[1])
    lst.append(wds[2])
    lst.append(wds[3])
    lst.append(wds[4])
    lst.append(wds[5])
    lst.append(wds[6])
    lst.append(wds[7])
    lst = list(dict.fromkeys(lst))
lst.sort()
print(lst)